// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTL_0wX5JI8hkx0NgEzzsoEvtalOL6E2g',
    appId: '1:892375007218:web:bf4657164c58300cd8356b',
    messagingSenderId: '892375007218',
    projectId: 'meucarrocerto-web',
    authDomain: 'meucarrocerto-web.firebaseapp.com',
    storageBucket: 'meucarrocerto-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-YEVLPwK8G-4vm8UaNnDqKJuvjFW2dM',
    appId: '1:892375007218:android:1b4d3f8cd88310bcd8356b',
    messagingSenderId: '892375007218',
    projectId: 'meucarrocerto-web',
    storageBucket: 'meucarrocerto-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4mUZY1AYBHHNiFDgOC5AiypRpC_lcdU',
    appId: '1:892375007218:ios:0acd63a5523b8c54d8356b',
    messagingSenderId: '892375007218',
    projectId: 'meucarrocerto-web',
    storageBucket: 'meucarrocerto-web.appspot.com',
    iosClientId: '892375007218-u1v1k6ingpmvd4e6r3gjun6t7h13uabr.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuCarroCerto',
  );
}
